[2025-01-24T18:32:07.651+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_to_redshift_copy_command.load_data_to_redshift manual__2025-01-24T18:32:04.060087+00:00 [queued]>
[2025-01-24T18:32:07.708+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_to_redshift_copy_command.load_data_to_redshift manual__2025-01-24T18:32:04.060087+00:00 [queued]>
[2025-01-24T18:32:07.710+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-01-24T18:32:07.725+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data_to_redshift> on 2025-01-24 18:32:04.060087+00:00
[2025-01-24T18:32:07.740+0000] {standard_task_runner.py:57} INFO - Started process 185 to run task
[2025-01-24T18:32:07.752+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 's3_to_redshift_copy_command', 'load_data_to_redshift', 'manual__2025-01-24T18:32:04.060087+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/load_user.py', '--cfg-path', '/tmp/tmpoc15336u']
[2025-01-24T18:32:07.757+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask load_data_to_redshift
[2025-01-24T18:32:07.782+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-24T18:32:07.827+0000] {task_command.py:415} INFO - Running <TaskInstance: s3_to_redshift_copy_command.load_data_to_redshift manual__2025-01-24T18:32:04.060087+00:00 [running]> on host e505ceb5f312
[2025-01-24T18:32:07.910+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_to_redshift_copy_command' AIRFLOW_CTX_TASK_ID='load_data_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-01-24T18:32:04.060087+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-24T18:32:04.060087+00:00'
[2025-01-24T18:32:07.934+0000] {base.py:73} INFO - Using connection ID 'redshift_default' for task execution.
[2025-01-24T18:32:08.067+0000] {sql.py:418} INFO - Running statement: 
    COPY public.user_details
    FROM 's3://datalakepax8/external/user_data.json'
    IAM_ROLE 'arn:aws:iam::654654432597:role/s3-access-to-redshift'  -- Replace with your IAM role ARN if necessary
    ACCESS_KEY_ID 'AKIAZQ3DR4VKSDXA6OEJ'
    SECRET_ACCESS_KEY 'rQI9COcUQdvA0mqE5HMoQ337TpmkLGe3CLzuNRd1'
    FORMAT AS JSON 'auto'
    IGNOREHEADER 1;  -- Add additional options based on your file format
    , parameters: None
[2025-01-24T18:32:08.088+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_user.py", line 27, in run_copy_command
    redshift_hook.run(copy_sql)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: conflicting or redundant options

[2025-01-24T18:32:08.098+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=s3_to_redshift_copy_command, task_id=load_data_to_redshift, execution_date=20250124T183204, start_date=20250124T183207, end_date=20250124T183208
[2025-01-24T18:32:08.107+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 13 for task load_data_to_redshift (conflicting or redundant options
; 185)
[2025-01-24T18:32:08.144+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-24T18:32:08.159+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
