[2025-01-24T18:42:02.377+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_to_redshift_copy_command.load_data_to_redshift manual__2025-01-24T18:41:59.817061+00:00 [queued]>
[2025-01-24T18:42:02.384+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_to_redshift_copy_command.load_data_to_redshift manual__2025-01-24T18:41:59.817061+00:00 [queued]>
[2025-01-24T18:42:02.384+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-01-24T18:42:02.393+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data_to_redshift> on 2025-01-24 18:41:59.817061+00:00
[2025-01-24T18:42:02.404+0000] {standard_task_runner.py:57} INFO - Started process 190 to run task
[2025-01-24T18:42:02.408+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 's3_to_redshift_copy_command', 'load_data_to_redshift', 'manual__2025-01-24T18:41:59.817061+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/load_user.py', '--cfg-path', '/tmp/tmpfxq8k28y']
[2025-01-24T18:42:02.411+0000] {standard_task_runner.py:85} INFO - Job 19: Subtask load_data_to_redshift
[2025-01-24T18:42:02.422+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-24T18:42:02.474+0000] {task_command.py:415} INFO - Running <TaskInstance: s3_to_redshift_copy_command.load_data_to_redshift manual__2025-01-24T18:41:59.817061+00:00 [running]> on host 423700a35b1c
[2025-01-24T18:42:02.551+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_to_redshift_copy_command' AIRFLOW_CTX_TASK_ID='load_data_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-01-24T18:41:59.817061+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-24T18:41:59.817061+00:00'
[2025-01-24T18:42:02.591+0000] {base.py:73} INFO - Using connection ID 'redshift_default' for task execution.
[2025-01-24T18:42:02.729+0000] {sql.py:418} INFO - Running statement: 
    COPY public.user_details
    FROM 's3://datalakepax8/external/user_data.json'
    IAM_ROLE 'arn:aws:iam::654654432597:role/s3-access-to-redshift'  
    FORMAT AS JSON 'auto'
    IGNOREHEADER 1;  
    , parameters: None
[2025-01-24T18:42:03.200+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_user.py", line 26, in run_copy_command
    redshift_hook.run(copy_sql)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InternalError_: Load into table 'user_details' failed.  Check 'sys_load_error_detail' system table for details.

[2025-01-24T18:42:03.215+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=s3_to_redshift_copy_command, task_id=load_data_to_redshift, execution_date=20250124T184159, start_date=20250124T184202, end_date=20250124T184203
[2025-01-24T18:42:03.226+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 19 for task load_data_to_redshift (Load into table 'user_details' failed.  Check 'sys_load_error_detail' system table for details.
; 190)
[2025-01-24T18:42:03.270+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-24T18:42:03.292+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
